### ISSUE TITLE
RPC error

### ISSUE THREAD

**Issue by devmasme** [rstormsf/multisender#22]
RPC error in https://rstormsf.github.io/multisender/#/4

MultiSender approval status is mined and then not working token transfer with under error massage

Kovan Network => MetaMask - RPC Error: Error: Transaction execution error.
Ropsten Network => MetaMask - RPC Error: Error: gas required exceeds allowance or always failing transaction

Thanks.

**Comment by rstormsf** [comment]
@devmasme Ropsten network doesn't have same gas limit as Ethereum mainnet. I noticed that issue sometimes as well.
@devmasme

**Comment by devmasme** [comment]
Thanks I solved it
