### ISSUE TITLE
Unable to call multisendtoken using remix IDE

### ISSUE THREAD

**Issue by Nitishkumar3211** [rstormsf/multisender#27]
Unable to call multisendtoken using remix getting error:- "Gas estimated failed".

**Comment by rstormsf** [comment]
Well, you need to explain how you use it. Most likely you are not proving correct parameters with correct ABIs, etc.

**Comment by lhalcyon** [comment]
I run across the same issue . !
![image](https://user-images.githubusercontent.com/21357951/66389038-fa7aef80-e9f9-11e9-93ec-49eff72b39bf.png)
![image](https://user-images.githubusercontent.com/21357951/66389054-08c90b80-e9fa-11e9-8a6a-71942f23c668.png)

**Comment by lhalcyon** [comment]
> I run across the same issue . !
> ![image](https://user-images.githubusercontent.com/21357951/66389038-fa7aef80-e9f9-11e9-93ec-49eff72b39bf.png)
> ![image](https://user-images.githubusercontent.com/21357951/66389054-08c90b80-e9fa-11e9-8a6a-71942f23c668.png)

wrong image .  multisendToken got failed!

**Comment by rstormsf** [comment]
Here is abi:
https://gist.github.com/rstormsf/881a0c437245efed4729e31d3b9d8da8
@lhalcyon

**Comment by lhalcyon** [comment]
@rstormsf  thank u for answering me :) .
yeah  I know the abi. I use Remix IDE send the tx and get the error above .  Also I run the code to send and get the same issue with multisendtoken .

Here is my steps.
1. I deploy the contract then call `initialized`   ,`0xf4b5afa5f450d2242d9e73077bd8f75bc949ae9f` is the contract on Rinkeby
2. Then I wanna transfer some tokenX from walletA to walletB and walletC.
3. So I use walletA to call `approve`  to tokenX
4. and wait 3 succeed , I use walletA to transfer token to B and C   , then get failed . 

the fee contract take is always ETH right ? , or cant be token as well ?

**Comment by rstormsf** [comment]
Sorry, I can only support you if you want to use https://multisender.app and mainnet address `0xA5025FABA6E70B84F74e9b1113e5F7F4E7f4859f`

**Comment by lhalcyon** [comment]
I deploy the contract code  , then run the js code on the GitHub  and get the same error result .

**Comment by lhalcyon** [comment]
em . I might found where the issue lies .   I copy the Tether USDT code to deploy without knowing they modify the `transfer` and `transferFrom` method of ERC20 . So  the multisender contract on the GitHub doesn't support the USDT type ERC20 , But the contract is upgradable , Author must have solved it , please share it with me ? @rstormsf

**Comment by rstormsf** [comment]
@lhalcyon yes I know the solution and current source code doesn't match what has been deployed on mainnet. Please use https://multisender.app to send USDT tokens
