### ISSUE TITLE
"NaN ETH" values on VIP tab

### ISSUE THREAD

**Issue by Jaimeloeuf** [rstormsf/multisender#30]
There value stated to buy VIP access is "NaN ETH", believe this to be wrong. Link to site is [here](https://multisender.app/vip/)

Refer to screen capture below
![image](https://user-images.githubusercontent.com/44993072/66992364-487bab80-f0fc-11e9-87c0-bdd336b457ae.png)

**Comment by rstormsf** [comment]
it just takes a few more seconds to load your metamask @Jaimeloeuf

**Comment by Jaimeloeuf** [comment]
@rstormsf thanks for the follow up, but should there be a way to let user's know that their wallet is not loading or what not? I am assuming you are referring Metamask not loaded and thus no web3 instance is injected into the DOM, which causes the price calculation (using web3 utils) to fail?

I suggest adding a section or popup to notify users of this issue to either ask them to restart their wallet or what not, as this message may be confusing especially to new users too! Thanks again.

**Comment by rstormsf** [comment]
@Jaimeloeuf I totally understand and I agree that we should do a much better job at it. 
I will assign a developer to fix it

**Comment by rstormsf** [comment]
@Jaimeloeuf fixed now

**Comment by Jaimeloeuf** [comment]
Thanks for the swift response! Appreciate it! 😊🙏
